// const dogBreedList = [
// "Affenpinscher","Afghan Hound","Airedale Terrier","Akita","Alaskan Klee Kai","Alaskan Malamute",
// "American Bulldog","American Cocker Spaniel","American Eskimo Dog","American Foxhound",
// "American Hairless Terrier","American Pit Bull Terrier","American Staffordshire Terrier",
// "Anatolian Shepherd Dog","Appenzeller Sennenhund","Australian Cattle Dog","Australian Kelpie",
// "Australian Shepherd","Australian Terrier","Azawakh",

// "Basenji","Basset Hound","Beagle","Bearded Collie","Beauceron","Bedlington Terrier",
// "Belgian Malinois","Belgian Sheepdog","Belgian Tervuren","Bernese Mountain Dog","Bichon Frise",
// "Black and Tan Coonhound","Bloodhound","Blue Lacy","Border Collie","Border Terrier","Borzoi",
// "Boston Terrier","Bouvier des Flandres","Boxer","Boykin Spaniel","Briard","Brittany",
// "Brussels Griffon","Bull Terrier","Bulldog","Bullmastiff",

// "Cairn Terrier","Canaan Dog","Cane Corso","Cardigan Welsh Corgi","Carolina Dog",
// "Catahoula Leopard Dog","Caucasian Shepherd Dog","Cavalier King Charles Spaniel",
// "Central Asian Shepherd Dog","Cesky Terrier","Chesapeake Bay Retriever","Chihuahua",
// "Chinese Crested","Chinese Shar-Pei","Chinook","Chow Chow","Clumber Spaniel","Cockapoo",
// "Cocker Spaniel","Collie","Coton de Tulear","Curly-Coated Retriever",

// "Dachshund","Dalmatian","Dandie Dinmont Terrier","Danish-Swedish Farmdog","Scottish Deerhound",
// "Doberman Pinscher","Dogo Argentino","Dogue de Bordeaux","Dutch Shepherd",

// "English Bulldog","English Cocker Spaniel","English Foxhound","English Setter",
// "English Springer Spaniel","English Toy Spaniel","Entlebucher Mountain Dog",
// "Estrela Mountain Dog","Eurasier",

// "Field Spaniel","Finnish Lapphund","Finnish Spitz","Flat-Coated Retriever",
// "Fox Terrier (Smooth)","Fox Terrier (Wire)","French Bulldog",

// "German Pinscher","German Shepherd","German Shorthaired Pointer",
// "German Wirehaired Pointer","Giant Schnauzer","Glen of Imaal Terrier",
// "Golden Retriever","Gordon Setter","Great Dane","Great Pyrenees",
// "Greater Swiss Mountain Dog","Greyhound",

// "Hamiltonstovare","Hanoverian Scenthound","Harrier","Havanese","Hokkaido",
// "Hovawart","Kuvasz","Vizsla","Wirehaired Vizsla","Siberian Husky",

// "Ibizan Hound","Icelandic Sheepdog","Indian Pariah Dog","Indian Spitz",
// "Irish Red and White Setter","Irish Setter","Irish Terrier","Irish Water Spaniel",
// "Irish Wolfhound","Italian Greyhound",

// "Jack Russell Terrier","Japanese Chin","Japanese Spitz","Jindo",

// "Kai Ken","Kangal Shepherd Dog","Karelian Bear Dog","Karst Shepherd","Keeshond",
// "Kerry Blue Terrier","Komondor","Kooikerhondje","Korean Mastiff","Kuvasz",

// "Labrador Retriever","Lagotto Romagnolo","Lakeland Terrier","Lancashire Heeler",
// "Leonberger","Lhasa Apso","Lowchen",

// "Maltese","Manchester Terrier","Maremma Sheepdog","Mastiff",
// "Miniature Bull Terrier","Miniature Pinscher","Miniature Schnauzer",
// "Mountain Cur","Mudi",

// "Neapolitan Mastiff","Newfoundland","Norfolk Terrier","Norwegian Buhund",
// "Norwegian Elkhound","Norwegian Lundehund","Norwich Terrier",
// "Nova Scotia Duck Tolling Retriever",

// "Old English Sheepdog","Otterhound",

// "Papillon","Parson Russell Terrier","Pekingese","Pembroke Welsh Corgi",
// "Peruvian Inca Orchid","Petit Basset Griffon Vendéen","Pharaoh Hound",
// "Plott Hound","Pointer","Polish Lowland Sheepdog","Pomeranian","Poodle",
// "Portuguese Podengo","Portuguese Water Dog","Pug","Puli","Pumi",

// "Qatari Saluki",

// "Rat Terrier","Redbone Coonhound","Rhodesian Ridgeback","Rottweiler",
// "Russian Toy","Russian Tsvetnaya Bolonka",

// "Saint Bernard","Saluki","Samoyed","Schipperke","Scottish Deerhound",
// "Scottish Terrier","Sealyham Terrier","Shar Pei","Shetland Sheepdog",
// "Shiba Inu","Shih Tzu","Siberian Husky","Silky Terrier","Skye Terrier",
// "Sloughi","Slovakian Rough-Haired Pointer","Small Munsterlander Pointer",
// "Soft Coated Wheaten Terrier","Spanish Water Dog","Spinone Italiano",
// "Stabyhoun","Staffordshire Bull Terrier","Standard Schnauzer",
// "Sussex Spaniel","Swedish Vallhund",

// "Taiwanese Dog","Tamaskan Dog","Thai Ridgeback","Tibetan Mastiff",
// "Tibetan Spaniel","Tibetan Terrier","Tosa Inu","Toy Fox Terrier",
// "Treeing Walker Coonhound",

// "Utonagan",

// "Vizsla","Volpino Italiano",

// "Weimaraner","Welsh Springer Spaniel","Welsh Terrier",
// "West Highland White Terrier","Whippet","White Swiss Shepherd",

// "Xoloitzcuintli",

// "Yakutian Laika","Yorkshire Terrier",

// "Zuchon"
// ];



const dogBreeds = [
{
  name: "Affenpinscher", lifeSpan: "12-15", origin: "Germany", type: "Toy",
  height_cm: { min: 23, max: 30 }, weight_kg: { min: 3, max: 6 }, coat: { length: "medium", type: "wire", shedding: "low" },
  temperament: ["playful","curious","bold"], anatomy: { body: "compact", ears: "erect", tail: "short", eyes: "round" }
},
{
  name: "Afghan Hound",
  lifeSpan: "12-18",
  origin: "Afghanistan",
  type: "Hound",
  height_cm: { min: 63, max: 74 },
  weight_kg: { min: 20, max: 30 },
  coat: { length: "long", type: "silky", shedding: "low" },
  temperament: ["independent","dignified","aloof"],
  anatomy: { body: "slim", ears: "long", tail: "curved", eyes: "almond" }
},
{
  name: "Airedale Terrier",
  lifeSpan: "11-14",
  origin: "England",
  type: "Terrier",
  height_cm: { min: 56, max: 61 },
  weight_kg: { min: 18, max: 29 },
  coat: { length: "medium", type: "wire", shedding: "low" },
  temperament: ["confident","smart","alert"],
  anatomy: { body: "balanced", ears: "folded", tail: "upright", eyes: "dark" }
},
{
  name: "Akita",
  lifeSpan: "10-13",
  origin: "Japan",
  type: "Working",
  height_cm: { min: 61, max: 71 },
  weight_kg: { min: 32, max: 59 },
  coat: { length: "medium", type: "double", shedding: "high" },
  temperament: ["loyal","protective","independent"],
  anatomy: { body: "large", ears: "erect", tail: "curled", eyes: "small" }
},
{
  name: "Alaskan Malamute",
  lifeSpan: "10-14",
  origin: "Alaska",
  type: "Working",
  height_cm: { min: 58, max: 64 },
  weight_kg: { min: 34, max: 43 },
  coat: { length: "medium", type: "double", shedding: "high" },
  temperament: ["friendly","strong","independent"],
  anatomy: { body: "powerful", ears: "erect", tail: "plumed", eyes: "almond" }
},
{
  name: "American Bulldog",
  lifeSpan: "10-12",
  origin: "USA",
  type: "Working",
  height_cm: { min: 50, max: 70 },
  weight_kg: { min: 30, max: 58 },
  coat: { length: "short", type: "single", shedding: "medium" },
  temperament: ["loyal","protective","energetic"],
  anatomy: { body: "muscular", ears: "drop", tail: "medium", eyes: "round" }
},
{
  name: "American Cocker Spaniel",
  lifeSpan: "10-14",
  origin: "USA",
  type: "Sporting",
  height_cm: { min: 34, max: 39 },
  weight_kg: { min: 9, max: 13 },
  coat: { length: "medium", type: "silky", shedding: "medium" },
  temperament: ["gentle","playful","affectionate"],
  anatomy: { body: "compact", ears: "long", tail: "medium", eyes: "round" }
},
{
  name: "American Eskimo Dog",
  lifeSpan: "12-15",
  origin: "USA",
  type: "Non-Sporting",
  height_cm: { min: 38, max: 48 },
  weight_kg: { min: 8, max: 16 },
  coat: { length: "long", type: "double", shedding: "high" },
  temperament: ["intelligent","alert","friendly"],
  anatomy: { body: "fluffy", ears: "erect", tail: "curled", eyes: "dark" }
},
{
  name: "American Foxhound",
  lifeSpan: "11-13",
  origin: "USA",
  type: "Hound",
  height_cm: { min: 53, max: 64 },
  weight_kg: { min: 20, max: 34 },
  coat: { length: "short", type: "single", shedding: "low" },
  temperament: ["independent","friendly","energetic"],
  anatomy: { body: "lean", ears: "drop", tail: "long", eyes: "brown" }
},
{
  name: "American Hairless Terrier",
  lifeSpan: "14-16",
  origin: "USA",
  type: "Terrier",
  height_cm: { min: 30, max: 40 },
  weight_kg: { min: 5, max: 8 },
  coat: { length: "hairless/short", type: "single", shedding: "none" },
  temperament: ["alert","playful","affectionate"],
  anatomy: { body: "small", ears: "erect", tail: "medium", eyes: "dark" }
},
{
  name: "American Pit Bull Terrier",
  lifeSpan: "12-16",
  origin: "USA",
  type: "Terrier",
  height_cm: { min: 43, max: 53 },
  weight_kg: { min: 16, max: 30 },
  coat: { length: "short", type: "single", shedding: "low" },
  temperament: ["loyal","strong","affectionate"],
  anatomy: { body: "muscular", ears: "rose", tail: "medium", eyes: "round" }
},
{
  name: "American Staffordshire Terrier",
  lifeSpan: "12-16",
  origin: "USA",
  type: "Terrier",
  height_cm: { min: 43, max: 48 },
  weight_kg: { min: 18, max: 32 },
  coat: { length: "short", type: "single", shedding: "low" },
  temperament: ["confident","loyal","friendly"],
  anatomy: { body: "muscular", ears: "rose", tail: "medium", eyes: "dark" }
},
{
  name: "Anatolian Shepherd Dog",
  lifeSpan: "11-13",
  origin: "Turkey",
  type: "Working",
  height_cm: { min: 71, max: 81 },
  weight_kg: { min: 40, max: 65 },
  coat: { length: "short/medium", type: "double", shedding: "medium" },
  temperament: ["protective","independent","calm"],
  anatomy: { body: "large", ears: "drop", tail: "curled", eyes: "almond" }
},
{
  name: "Appenzeller Sennenhund",
  lifeSpan: "12-14",
  origin: "Switzerland",
  type: "Working",
  height_cm: { min: 48, max: 58 },
  weight_kg: { min: 22, max: 32 },
  coat: { length: "short", type: "double", shedding: "medium" },
  temperament: ["energetic","loyal","alert"],
  anatomy: { body: "athletic", ears: "drop", tail: "curled", eyes: "dark" }
},
{
  name: "Australian Cattle Dog",
  lifeSpan: "12-16",
  origin: "Australia",
  type: "Herding",
  height_cm: { min: 43, max: 51 },
  weight_kg: { min: 15, max: 22 },
  coat: { length: "short", type: "double", shedding: "medium" },
  temperament: ["energetic","intelligent","loyal"],
  anatomy: { body: "compact", ears: "erect", tail: "medium", eyes: "dark" }
},
{
  name: "Australian Kelpie",
  lifeSpan: "12-15",
  origin: "Australia",
  type: "Herding",
  height_cm: { min: 43, max: 51 },
  weight_kg: { min: 14, max: 21 },
  coat: { length: "short", type: "double", shedding: "medium" },
  temperament: ["active","intelligent","alert"],
  anatomy: { body: "lean", ears: "erect", tail: "medium", eyes: "brown" }
},
{
  name: "Australian Shepherd",
  lifeSpan: "12-15",
  origin: "USA",
  type: "Herding",
  height_cm: { min: 46, max: 58 },
  weight_kg: { min: 16, max: 32 },
  coat: { length: "medium", type: "double", shedding: "medium" },
  temperament: ["intelligent","energetic","loyal"],
  anatomy: { body: "athletic", ears: "semi-erect", tail: "bob/long", eyes: "varied" }
},
{
  name: "Australian Terrier",
  lifeSpan: "12-15",
  origin: "Australia",
  type: "Terrier",
  height_cm: { min: 23, max: 28 },
  weight_kg: { min: 5, max: 7 },
  coat: { length: "medium", type: "wire", shedding: "low" },
  temperament: ["alert","friendly","spirited"],
  anatomy: { body: "small", ears: "erect", tail: "short", eyes: "dark" }
},
{
  name: "Azawakh",
  lifeSpan: "12-15",
  origin: "West Africa",
  type: "Hound",
  height_cm: { min: 60, max: 74 },
  weight_kg: { min: 15, max: 25 },
  coat: { length: "short", type: "single", shedding: "low" },
  temperament: ["independent","loyal","reserved"],
  anatomy: { body: "slender", ears: "drop", tail: "long", eyes: "dark" }
},
{
  name: "Basenji",
  lifeSpan: "12-16",
  origin: "Central Africa",
  type: "Hound",
  height_cm: { min: 40, max: 43 },
  weight_kg: { min: 9, max: 11 },
  coat: { length: "short", type: "single", shedding: "low" },
  temperament: ["independent","alert","curious"],
  anatomy: { body: "compact", ears: "erect", tail: "curled", eyes: "almond" }
},
{
  name: "Basset Hound",
  lifeSpan: "10-12",
  origin: "France",
  type: "Hound",
  height_cm: { min: 28, max: 38 },
  weight_kg: { min: 20, max: 29 },
  coat: { length: "short", type: "single", shedding: "medium" },
  temperament: ["gentle","friendly","lazy"],
  anatomy: { body: "long", ears: "very long", tail: "medium", eyes: "droopy" }
},

{
  name: "Beagle",
  lifeSpan: "12-15",
  origin: "England",
  type: "Hound",
  height_cm: { min: 33, max: 41 },
  weight_kg: { min: 9, max: 14 },
  coat: { length: "short", type: "single", shedding: "medium" },
  temperament: ["friendly","curious","playful"],
  anatomy: { body: "compact", ears: "long floppy", tail: "medium", eyes: "large" }
},
{
  name: "Bearded Collie",
  lifeSpan: "12-14",
  origin: "Scotland",
  type: "Herding",
  height_cm: { min: 51, max: 56 },
  weight_kg: { min: 18, max: 27 },
  coat: { length: "long", type: "double", shedding: "medium" },
  temperament: ["friendly","energetic","playful"],
  anatomy: { body: "lean", ears: "drop", tail: "long", eyes: "expressive" }
},
{
  name: "Beauceron",
  lifeSpan: "10-12",
  origin: "France",
  type: "Working",
  height_cm: { min: 61, max: 70 },
  weight_kg: { min: 30, max: 45 },
  coat: { length: "short", type: "double", shedding: "medium" },
  temperament: ["loyal","protective","intelligent"],
  anatomy: { body: "muscular", ears: "drop/erect", tail: "long", eyes: "dark" }
},
{
  name: "Bedlington Terrier",
  lifeSpan: "12-16",
  origin: "England",
  type: "Terrier",
  height_cm: { min: 38, max: 44 },
  weight_kg: { min: 8, max: 10 },
  coat: { length: "curly", type: "single", shedding: "low" },
  temperament: ["gentle","affectionate","spirited"],
  anatomy: { body: "arched", ears: "drop", tail: "tapered", eyes: "small" }
},
{
  name: "Belgian Malinois",
  lifeSpan: "12-14",
  origin: "Belgium",
  type: "Working",
  height_cm: { min: 56, max: 66 },
  weight_kg: { min: 20, max: 30 },
  coat: { length: "short", type: "double", shedding: "medium" },
  temperament: ["alert","energetic","protective"],
  anatomy: { body: "athletic", ears: "erect", tail: "medium", eyes: "dark" }
},
{
  name: "Belgian Sheepdog",
  lifeSpan: "12-14",
  origin: "Belgium",
  type: "Herding",
  height_cm: { min: 56, max: 66 },
  weight_kg: { min: 20, max: 30 },
  coat: { length: "long", type: "double", shedding: "medium" },
  temperament: ["loyal","intelligent","alert"],
  anatomy: { body: "elegant", ears: "erect", tail: "long", eyes: "dark" }
},
{
  name: "Belgian Tervuren",
  lifeSpan: "12-14",
  origin: "Belgium",
  type: "Herding",
  height_cm: { min: 56, max: 66 },
  weight_kg: { min: 20, max: 30 },
  coat: { length: "long", type: "double", shedding: "medium" },
  temperament: ["intelligent","active","loyal"],
  anatomy: { body: "athletic", ears: "erect", tail: "long", eyes: "dark" }
},
{
  name: "Bernese Mountain Dog",
  lifeSpan: "7-10",
  origin: "Switzerland",
  type: "Working",
  height_cm: { min: 58, max: 70 },
  weight_kg: { min: 35, max: 55 },
  coat: { length: "long", type: "double", shedding: "high" },
  temperament: ["gentle","loyal","calm"],
  anatomy: { body: "large", ears: "drop", tail: "bushy", eyes: "dark" }
},
{
  name: "Bichon Frise",
  lifeSpan: "12-15",
  origin: "France",
  type: "Toy",
  height_cm: { min: 23, max: 30 },
  weight_kg: { min: 5, max: 8 },
  coat: { length: "curly", type: "double", shedding: "low" },
  temperament: ["cheerful","playful","friendly"],
  anatomy: { body: "small", ears: "drop", tail: "curled", eyes: "round dark" }
},
{
  name: "Black and Tan Coonhound",
  lifeSpan: "10-12",
  origin: "USA",
  type: "Hound",
  height_cm: { min: 58, max: 69 },
  weight_kg: { min: 25, max: 34 },
  coat: { length: "short", type: "single", shedding: "medium" },
  temperament: ["friendly","independent","easygoing"],
  anatomy: { body: "strong", ears: "long drop", tail: "long", eyes: "dark" }
},
{
  name: "Bloodhound",
  lifeSpan: "10-12",
  origin: "Belgium",
  type: "Hound",
  height_cm: { min: 58, max: 69 },
  weight_kg: { min: 36, max: 50 },
  coat: { length: "short", type: "single", shedding: "medium" },
  temperament: ["gentle","stubborn","friendly"],
  anatomy: { body: "large", ears: "very long", tail: "long", eyes: "droopy" }
},
{
  name: "Blue Lacy",
  lifeSpan: "12-16",
  origin: "USA",
  type: "Working",
  height_cm: { min: 46, max: 53 },
  weight_kg: { min: 14, max: 23 },
  coat: { length: "short", type: "single", shedding: "low" },
  temperament: ["energetic","intelligent","alert"],
  anatomy: { body: "lean", ears: "drop", tail: "long", eyes: "amber" }
},
{
  name: "Border Collie",
  lifeSpan: "12-15",
  origin: "UK",
  type: "Herding",
  height_cm: { min: 46, max: 56 },
  weight_kg: { min: 12, max: 20 },
  coat: { length: "medium", type: "double", shedding: "medium" },
  temperament: ["intelligent","energetic","focused"],
  anatomy: { body: "athletic", ears: "semi-erect", tail: "long", eyes: "oval" }
},
{
  name: "Border Terrier",
  lifeSpan: "12-15",
  origin: "United Kingdom",
  type: "Terrier",
  height_cm: { min: 28, max: 40 },
  weight_kg: { min: 5, max: 7 },
  coat: { length: "short", type: "wire", shedding: "low" },
  temperament: ["friendly","alert","affectionate"],
  anatomy: { body: "compact", ears: "drop", tail: "short", eyes: "dark" }
},
{
  name: "Borzoi",
  lifeSpan: "10-12",
  origin: "Russia",
  type: "Hound",
  height_cm: { min: 68, max: 85 },
  weight_kg: { min: 25, max: 48 },
  coat: { length: "long", type: "silky", shedding: "medium" },
  temperament: ["gentle","independent","quiet"],
  anatomy: { body: "slender", ears: "small", tail: "long", eyes: "dark" }
},
{
  name: "Boston Terrier",
  lifeSpan: "11-13",
  origin: "USA",
  type: "Non-Sporting",
  height_cm: { min: 38, max: 43 },
  weight_kg: { min: 6, max: 11 },
  coat: { length: "short", type: "single", shedding: "low" },
  temperament: ["friendly","lively","intelligent"],
  anatomy: { body: "compact", ears: "erect", tail: "short", eyes: "large" }
},
{
  name: "Bouvier des Flandres",
  lifeSpan: "10-12",
  origin: "Belgium",
  type: "Working",
  height_cm: { min: 59, max: 69 },
  weight_kg: { min: 27, max: 40 },
  coat: { length: "medium", type: "double", shedding: "medium" },
  temperament: ["loyal","protective","calm"],
  anatomy: { body: "powerful", ears: "drop", tail: "short", eyes: "dark" }
},
{
  name: "Boxer",
  lifeSpan: "10-12",
  origin: "Germany",
  type: "Working",
  height_cm: { min: 53, max: 63 },
  weight_kg: { min: 25, max: 32 },
  coat: { length: "short", type: "single", shedding: "low" },
  temperament: ["playful","loyal","energetic"],
  anatomy: { body: "muscular", ears: "natural/cropped", tail: "short", eyes: "dark" }
},
{
  name: "Bulldog",
  lifeSpan: "8-10",
  origin: "England",
  type: "Non-Sporting",
  height_cm: { min: 31, max: 40 },
  weight_kg: { min: 18, max: 25 },
  coat: { length: "short", type: "single", shedding: "medium" },
  temperament: ["calm","friendly","stubborn"],
  anatomy: { body: "stocky", ears: "small fold", tail: "short", eyes: "round" }
},
{
  name: "Boykin Spaniel",
  lifeSpan: "10-15",
  origin: "USA",
  type: "Sporting",
  height_cm: { min: 36, max: 46 },
  weight_kg: { min: 11, max: 18 },
  coat: { length: "medium", type: "wavy", shedding: "medium" },
  temperament: ["friendly","energetic","eager"],
  anatomy: { body: "compact", ears: "long", tail: "medium", eyes: "brown" }
},
{
  name: "Briard",
  lifeSpan: "10-12",
  origin: "France",
  type: "Herding",
  height_cm: { min: 56, max: 69 },
  weight_kg: { min: 25, max: 40 },
  coat: { length: "long", type: "double", shedding: "medium" },
  temperament: ["loyal","protective","intelligent"],
  anatomy: { body: "strong", ears: "high set", tail: "long", eyes: "dark" }
},
{
  name: "Brittany",
  lifeSpan: "12-14",
  origin: "France",
  type: "Sporting",
  height_cm: { min: 44, max: 52 },
  weight_kg: { min: 14, max: 20 },
  coat: { length: "medium", type: "single", shedding: "low" },
  temperament: ["energetic","friendly","alert"],
  anatomy: { body: "compact", ears: "drop", tail: "short", eyes: "amber" }
},
{
  name: "Brussels Griffon",
  lifeSpan: "12-15",
  origin: "Belgium",
  type: "Toy",
  height_cm: { min: 18, max: 25 },
  weight_kg: { min: 3, max: 6 },
  coat: { length: "short/rough", type: "single", shedding: "low" },
  temperament: ["affectionate","alert","sensitive"],
  anatomy: { body: "small", ears: "semi-erect", tail: "short", eyes: "large" }
},
{
  name: "Bull Terrier",
  lifeSpan: "12-13",
  origin: "England",
  type: "Terrier",
  height_cm: { min: 53, max: 56 },
  weight_kg: { min: 22, max: 38 },
  coat: { length: "short", type: "single", shedding: "low" },
  temperament: ["playful","strong","stubborn"],
  anatomy: { body: "muscular", ears: "erect", tail: "short", eyes: "small" }
},
{
  name: "Bullmastiff",
  lifeSpan: "7-10",
  origin: "England",
  type: "Working",
  height_cm: { min: 61, max: 69 },
  weight_kg: { min: 45, max: 60 },
  coat: { length: "short", type: "single", shedding: "low" },
  temperament: ["protective","loyal","calm"],
  anatomy: { body: "powerful", ears: "drop", tail: "medium", eyes: "dark" }
},
{
  name: "Cairn Terrier",
  lifeSpan: "13-15",
  origin: "Scotland",
  type: "Terrier",
  height_cm: { min: 23, max: 33 },
  weight_kg: { min: 6, max: 8 },
  coat: { length: "medium", type: "wire", shedding: "low" },
  temperament: ["alert","playful","curious"],
  anatomy: { body: "compact", ears: "erect", tail: "short", eyes: "dark" }
},
{
  name: "Canaan Dog",
  lifeSpan: "12-15",
  origin: "Israel",
  type: "Working",
  height_cm: { min: 50, max: 60 },
  weight_kg: { min: 18, max: 25 },
  coat: { length: "short", type: "double", shedding: "medium" },
  temperament: ["alert","loyal","independent"],
  anatomy: { body: "balanced", ears: "erect", tail: "curled", eyes: "almond" }
},
{
  name: "Cane Corso",
  lifeSpan: "9-12",
  origin: "Italy",
  type: "Working",
  height_cm: { min: 60, max: 68 },
  weight_kg: { min: 40, max: 50 },
  coat: { length: "short", type: "single", shedding: "low" },
  temperament: ["protective","confident","loyal"],
  anatomy: { body: "muscular", ears: "drop", tail: "medium", eyes: "almond" }
},
{
  name: "Cardigan Welsh Corgi",
  lifeSpan: "12-15",
  origin: "Wales",
  type: "Herding",
  height_cm: { min: 25, max: 33 },
  weight_kg: { min: 11, max: 17 },
  coat: { length: "medium", type: "double", shedding: "medium" },
  temperament: ["friendly","loyal","active"],
  anatomy: { body: "long", ears: "large erect", tail: "long", eyes: "round" }
},
{
  name: "Carolina Dog",
  lifeSpan: "12-15",
  origin: "USA",
  type: "Pariah",
  height_cm: { min: 45, max: 55 },
  weight_kg: { min: 15, max: 20 },
  coat: { length: "short", type: "single", shedding: "low" },
  temperament: ["shy","loyal","independent"],
  anatomy: { body: "lean", ears: "erect", tail: "curved", eyes: "almond" }
},
{
  name: "Catahoula Leopard Dog",
  lifeSpan: "10-14",
  origin: "USA",
  type: "Working",
  height_cm: { min: 51, max: 66 },
  weight_kg: { min: 18, max: 41 },
  coat: { length: "short", type: "single", shedding: "medium" },
  temperament: ["energetic","independent","loyal"],
  anatomy: { body: "athletic", ears: "drop", tail: "long", eyes: "varied" }
},
{
  name: "Caucasian Shepherd Dog",
  lifeSpan: "10-12",
  origin: "Russia",
  type: "Working",
  height_cm: { min: 64, max: 75 },
  weight_kg: { min: 45, max: 70 },
  coat: { length: "long", type: "double", shedding: "high" },
  temperament: ["protective","fearless","strong"],
  anatomy: { body: "giant", ears: "drop", tail: "bushy", eyes: "deep" }
},
{
  name: "Cavalier King Charles Spaniel",
  lifeSpan: "12-15",
  origin: "England",
  type: "Toy",
  height_cm: { min: 30, max: 33 },
  weight_kg: { min: 5, max: 8 },
  coat: { length: "medium", type: "silky", shedding: "medium" },
  temperament: ["affectionate","gentle","friendly"],
  anatomy: { body: "small", ears: "long", tail: "feathered", eyes: "large" }
},
{
  name: "Central Asian Shepherd Dog",
  lifeSpan: "10-12",
  origin: "Central Asia",
  type: "Working",
  height_cm: { min: 65, max: 78 },
  weight_kg: { min: 40, max: 80 },
  coat: { length: "medium", type: "double", shedding: "medium" },
  temperament: ["protective","independent","calm"],
  anatomy: { body: "strong", ears: "drop", tail: "thick", eyes: "dark" }
},
{
  name: "Cesky Terrier",
  lifeSpan: "12-15",
  origin: "Czech Republic",
  type: "Terrier",
  height_cm: { min: 25, max: 32 },
  weight_kg: { min: 6, max: 10 },
  coat: { length: "long", type: "silky", shedding: "low" },
  temperament: ["calm","friendly","alert"],
  anatomy: { body: "small", ears: "drop", tail: "medium", eyes: "dark" }
},
{
  name: "Chesapeake Bay Retriever",
  lifeSpan: "10-13",
  origin: "USA",
  type: "Sporting",
  height_cm: { min: 53, max: 66 },
  weight_kg: { min: 25, max: 36 },
  coat: { length: "short", type: "double oily", shedding: "medium" },
  temperament: ["loyal","energetic","protective"],
  anatomy: { body: "strong", ears: "small", tail: "medium", eyes: "amber" }
},
{
  name: "Chihuahua",
  lifeSpan: "14-17",
  origin: "Mexico",
  type: "Toy",
  height_cm: { min: 15, max: 23 },
  weight_kg: { min: 1.5, max: 3 },
  coat: { length: "short/long", type: "single", shedding: "low" },
  temperament: ["alert","bold","lively"],
  anatomy: { body: "tiny", ears: "large erect", tail: "curved", eyes: "round" }
},
{
  name: "Chinese Crested",
  lifeSpan: "13-18",
  origin: "China",
  type: "Toy",
  height_cm: { min: 28, max: 33 },
  weight_kg: { min: 3, max: 5 },
  coat: { length: "hairless/long", type: "single", shedding: "low" },
  temperament: ["affectionate","lively","alert"],
  anatomy: { body: "small", ears: "large erect", tail: "feathered", eyes: "dark" }
},
{
  name: "Chinese Shar-Pei",
  lifeSpan: "8-12",
  origin: "China",
  type: "Non-Sporting",
  height_cm: { min: 44, max: 51 },
  weight_kg: { min: 18, max: 30 },
  coat: { length: "short", type: "bristly", shedding: "low" },
  temperament: ["independent","loyal","calm"],
  anatomy: { body: "wrinkled", ears: "small", tail: "curled", eyes: "deep" }
},
{
  name: "Chinook",
  lifeSpan: "12-15",
  origin: "USA",
  type: "Working",
  height_cm: { min: 53, max: 69 },
  weight_kg: { min: 25, max: 41 },
  coat: { length: "medium", type: "double", shedding: "medium" },
  temperament: ["friendly","gentle","loyal"],
  anatomy: { body: "athletic", ears: "drop", tail: "medium", eyes: "brown" }
},
{
  name: "Chow Chow",
  lifeSpan: "9-15",
  origin: "China",
  type: "Non-Sporting",
  height_cm: { min: 43, max: 51 },
  weight_kg: { min: 20, max: 32 },
  coat: { length: "long", type: "double", shedding: "high" },
  temperament: ["independent","loyal","reserved"],
  anatomy: { body: "compact", ears: "small erect", tail: "curled", eyes: "deep" }
},
{
  name: "Clumber Spaniel",
  lifeSpan: "10-12",
  origin: "England",
  type: "Sporting",
  height_cm: { min: 43, max: 51 },
  weight_kg: { min: 25, max: 39 },
  coat: { length: "medium", type: "dense", shedding: "medium" },
  temperament: ["gentle","calm","loyal"],
  anatomy: { body: "heavy", ears: "long", tail: "medium", eyes: "deep" }
},
{
  name: "Cockapoo",
  lifeSpan: "12-15",
  origin: "USA",
  type: "Companion / Designer",
  height_cm: { min: 25, max: 38 },
  weight_kg: { min: 5, max: 11 },
  coat: { length: "curly/wavy", type: "soft", shedding: "low" },
  temperament: ["friendly","playful","affectionate"],
  anatomy: { body: "small-medium", ears: "long", tail: "medium", eyes: "round" },
  isHybrid: true,
  parents: ["Cocker Spaniel","Poodle"]
},
{
  name: "Cocker Spaniel",
  lifeSpan: "12-15",
  origin: "England",
  type: "Sporting",
  height_cm: { min: 34, max: 41 },
  weight_kg: { min: 9, max: 14 },
  coat: { length: "medium", type: "silky", shedding: "medium" },
  temperament: ["friendly","playful","gentle"],
  anatomy: { body: "compact", ears: "long", tail: "medium", eyes: "round" }
},
{
  name: "Collie",
  lifeSpan: "12-14",
  origin: "Scotland",
  type: "Herding",
  height_cm: { min: 51, max: 66 },
  weight_kg: { min: 18, max: 30 },
  coat: { length: "long", type: "double", shedding: "medium" },
  temperament: ["loyal","gentle","intelligent"],
  anatomy: { body: "elegant", ears: "semi-erect", tail: "long", eyes: "almond" }
},
{
  name: "Coton de Tulear",
  lifeSpan: "14-16",
  origin: "Madagascar",
  type: "Toy",
  height_cm: { min: 22, max: 30 },
  weight_kg: { min: 4, max: 6 },
  coat: { length: "long", type: "cotton-like", shedding: "low" },
  temperament: ["happy","playful","affectionate"],
  anatomy: { body: "small", ears: "drop", tail: "curved", eyes: "dark" }
},
{
  name: "Curly-Coated Retriever",
  lifeSpan: "10-12",
  origin: "England",
  type: "Sporting",
  height_cm: { min: 58, max: 69 },
  weight_kg: { min: 25, max: 36 },
  coat: { length: "curly", type: "single", shedding: "low" },
  temperament: ["confident","independent","friendly"],
  anatomy: { body: "athletic", ears: "small", tail: "straight", eyes: "dark" }
},
{
  name: "Dachshund",
  lifeSpan: "12-16",
  origin: "Germany",
  type: "Hound",
  height_cm: { min: 20, max: 27 },
  weight_kg: { min: 7, max: 15 },
  coat: { length: "short/long/wire", type: "single", shedding: "medium" },
  temperament: ["playful","stubborn","curious"],
  anatomy: { body: "long", ears: "long floppy", tail: "medium", eyes: "oval" }
},
{
  name: "Dalmatian",
  lifeSpan: "11-13",
  origin: "Croatia",
  type: "Non-Sporting",
  height_cm: { min: 48, max: 61 },
  weight_kg: { min: 16, max: 32 },
  coat: { length: "short", type: "single", shedding: "high" },
  temperament: ["energetic","friendly","alert"],
  anatomy: { body: "athletic", ears: "drop", tail: "long", eyes: "round" }
},
{
  name: "Dandie Dinmont Terrier",
  lifeSpan: "12-15",
  origin: "Scotland",
  type: "Terrier",
  height_cm: { min: 20, max: 28 },
  weight_kg: { min: 8, max: 11 },
  coat: { length: "medium", type: "wire", shedding: "low" },
  temperament: ["calm","independent","affectionate"],
  anatomy: { body: "long", ears: "pendant", tail: "curved", eyes: "large" }
},
{
  name: "Danish-Swedish Farmdog",
  lifeSpan: "11-13",
  origin: "Denmark/Sweden",
  type: "Working",
  height_cm: { min: 30, max: 39 },
  weight_kg: { min: 7, max: 12 },
  coat: { length: "short", type: "single", shedding: "low" },
  temperament: ["friendly","active","alert"],
  anatomy: { body: "compact", ears: "semi-drop", tail: "medium", eyes: "round" }
},
{
  name: "Scottish Deerhound",
  lifeSpan: "8-11",
  origin: "Scotland",
  type: "Hound",
  height_cm: { min: 71, max: 81 },
  weight_kg: { min: 34, max: 50 },
  coat: { length: "rough", type: "single", shedding: "low" },
  temperament: ["gentle","friendly","dignified"],
  anatomy: { body: "tall", ears: "folded", tail: "long", eyes: "dark" }
},
{
  name: "Doberman Pinscher",
  lifeSpan: "10-12",
  origin: "Germany",
  type: "Working",
  height_cm: { min: 63, max: 72 },
  weight_kg: { min: 30, max: 45 },
  coat: { length: "short", type: "single", shedding: "low" },
  temperament: ["loyal","fearless","alert"],
  anatomy: { body: "sleek", ears: "erect", tail: "short", eyes: "almond" }
},
{
  name: "Dogo Argentino",
  lifeSpan: "9-15",
  origin: "Argentina",
  type: "Working",
  height_cm: { min: 60, max: 68 },
  weight_kg: { min: 35, max: 45 },
  coat: { length: "short", type: "single", shedding: "low" },
  temperament: ["brave","loyal","protective"],
  anatomy: { body: "muscular", ears: "drop", tail: "long", eyes: "dark" }
},
{
  name: "Dogue de Bordeaux",
  lifeSpan: "5-8",
  origin: "France",
  type: "Working",
  height_cm: { min: 58, max: 69 },
  weight_kg: { min: 45, max: 65 },
  coat: { length: "short", type: "single", shedding: "low" },
  temperament: ["calm","loyal","protective"],
  anatomy: { body: "massive", ears: "drop", tail: "thick", eyes: "oval" }
},
{
  name: "Dutch Shepherd",
  lifeSpan: "11-14",
  origin: "Netherlands",
  type: "Herding",
  height_cm: { min: 55, max: 62 },
  weight_kg: { min: 20, max: 32 },
  coat: { length: "short/long/wire", type: "double", shedding: "medium" },
  temperament: ["intelligent","loyal","alert"],
  anatomy: { body: "athletic", ears: "erect", tail: "long", eyes: "almond" }
},

{
  name: "English Bulldog",
  lifeSpan: "8-10",
  origin: "England",
  type: "Non-Sporting",
  height_cm: { min: 31, max: 40 },
  weight_kg: { min: 18, max: 25 },
  coat: { length: "short", type: "single", shedding: "medium" },
  temperament: ["calm","friendly","stubborn"],
  anatomy: { body: "stocky", ears: "folded", tail: "short", eyes: "round" }
},
{
  name: "English Cocker Spaniel",
  lifeSpan: "12-15",
  origin: "England",
  type: "Sporting",
  height_cm: { min: 38, max: 43 },
  weight_kg: { min: 12, max: 16 },
  coat: { length: "medium", type: "silky", shedding: "medium" },
  temperament: ["friendly","playful","gentle"],
  anatomy: { body: "compact", ears: "long", tail: "medium", eyes: "round" }
},
{
  name: "English Foxhound",
  lifeSpan: "10-13",
  origin: "England",
  type: "Hound",
  height_cm: { min: 58, max: 64 },
  weight_kg: { min: 25, max: 34 },
  coat: { length: "short", type: "single", shedding: "medium" },
  temperament: ["friendly","active","social"],
  anatomy: { body: "lean", ears: "drop", tail: "long", eyes: "brown" }
},
{
  name: "English Setter",
  lifeSpan: "10-12",
  origin: "England",
  type: "Sporting",
  height_cm: { min: 61, max: 68 },
  weight_kg: { min: 20, max: 36 },
  coat: { length: "long", type: "silky", shedding: "medium" },
  temperament: ["gentle","friendly","energetic"],
  anatomy: { body: "elegant", ears: "long", tail: "feathered", eyes: "oval" }
},
{
  name: "English Springer Spaniel",
  lifeSpan: "12-14",
  origin: "England",
  type: "Sporting",
  height_cm: { min: 48, max: 56 },
  weight_kg: { min: 18, max: 25 },
  coat: { length: "medium", type: "double", shedding: "medium" },
  temperament: ["friendly","energetic","obedient"],
  anatomy: { body: "balanced", ears: "long", tail: "medium", eyes: "oval" }
},
{
  name: "English Toy Spaniel",
  lifeSpan: "10-12",
  origin: "England",
  type: "Toy",
  height_cm: { min: 23, max: 28 },
  weight_kg: { min: 3.5, max: 6 },
  coat: { length: "long", type: "silky", shedding: "medium" },
  temperament: ["affectionate","calm","friendly"],
  anatomy: { body: "small", ears: "long", tail: "short", eyes: "large" }
},
{
  name: "Entlebucher Mountain Dog",
  lifeSpan: "11-13",
  origin: "Switzerland",
  type: "Herding",
  height_cm: { min: 42, max: 52 },
  weight_kg: { min: 20, max: 30 },
  coat: { length: "short", type: "double", shedding: "medium" },
  temperament: ["loyal","energetic","protective"],
  anatomy: { body: "compact", ears: "drop", tail: "short", eyes: "dark" }
},
{
  name: "Eurasier",
  lifeSpan: "12-14",
  origin: "Germany",
  type: "Non-Sporting",
  height_cm: { min: 48, max: 60 },
  weight_kg: { min: 18, max: 32 },
  coat: { length: "medium", type: "double", shedding: "medium" },
  temperament: ["calm","loyal","reserved"],
  anatomy: { body: "balanced", ears: "erect", tail: "curled", eyes: "dark" }
},

{
  name: "Field Spaniel",
  lifeSpan: "10-12",
  origin: "England",
  type: "Sporting",
  height_cm: { min: 43, max: 46 },
  weight_kg: { min: 16, max: 25 },
  coat: { length: "medium", type: "silky", shedding: "medium" },
  temperament: ["gentle","loyal","active"],
  anatomy: { body: "long", ears: "long", tail: "medium", eyes: "oval" }
},
{
  name: "Finnish Lapphund",
  lifeSpan: "12-15",
  origin: "Finland",
  type: "Herding",
  height_cm: { min: 41, max: 52 },
  weight_kg: { min: 15, max: 24 },
  coat: { length: "long", type: "double", shedding: "high" },
  temperament: ["friendly","calm","alert"],
  anatomy: { body: "compact", ears: "erect", tail: "curled", eyes: "oval" }
},
{
  name: "Finnish Spitz",
  lifeSpan: "12-14",
  origin: "Finland",
  type: "Hound",
  height_cm: { min: 39, max: 50 },
  weight_kg: { min: 7, max: 16 },
  coat: { length: "medium", type: "double", shedding: "medium" },
  temperament: ["alert","lively","independent"],
  anatomy: { body: "square", ears: "erect", tail: "curled", eyes: "dark" }
},
{
  name: "Flat-Coated Retriever",
  lifeSpan: "8-10",
  origin: "England",
  type: "Sporting",
  height_cm: { min: 56, max: 62 },
  weight_kg: { min: 25, max: 36 },
  coat: { length: "medium", type: "double", shedding: "medium" },
  temperament: ["playful","friendly","energetic"],
  anatomy: { body: "athletic", ears: "drop", tail: "long", eyes: "oval" }
},
{
  name: "Fox Terrier (Smooth)",
  lifeSpan: "12-15",
  origin: "England",
  type: "Terrier",
  height_cm: { min: 36, max: 39 },
  weight_kg: { min: 7, max: 8 },
  coat: { length: "short", type: "single", shedding: "low" },
  temperament: ["bold","active","alert"],
  anatomy: { body: "compact", ears: "folded", tail: "upright", eyes: "dark" }
},
{
  name: "Fox Terrier (Wire)",
  lifeSpan: "12-15",
  origin: "England",
  type: "Terrier",
  height_cm: { min: 36, max: 39 },
  weight_kg: { min: 7, max: 8 },
  coat: { length: "wire", type: "single", shedding: "low" },
  temperament: ["energetic","bold","playful"],
  anatomy: { body: "compact", ears: "folded", tail: "upright", eyes: "dark" }
},
{
  name: "French Bulldog",
  lifeSpan: "10-12",
  origin: "France",
  type: "Non-Sporting",
  height_cm: { min: 28, max: 33 },
  weight_kg: { min: 8, max: 14 },
  coat: { length: "short", type: "single", shedding: "low" },
  temperament: ["playful","affectionate","friendly"],
  anatomy: { body: "compact", ears: "bat ears", tail: "short", eyes: "round" }
},
{
  name: "German Pinscher",
  lifeSpan: "12-14",
  origin: "Germany",
  type: "Working",
  height_cm: { min: 45, max: 50 },
  weight_kg: { min: 14, max: 20 },
  coat: { length: "short", type: "single", shedding: "low" },
  temperament: ["alert","loyal","energetic"],
  anatomy: { body: "muscular", ears: "folded", tail: "medium", eyes: "dark" }
},
{
  name: "German Shepherd",
  lifeSpan: "9-13",
  origin: "Germany",
  type: "Herding",
  height_cm: { min: 55, max: 65 },
  weight_kg: { min: 22, max: 40 },
  coat: { length: "medium/long", type: "double", shedding: "high" },
  temperament: ["intelligent","loyal","protective"],
  anatomy: { body: "strong", ears: "erect", tail: "bushy", eyes: "almond" }
},
{
  name: "German Shorthaired Pointer",
  lifeSpan: "10-12",
  origin: "Germany",
  type: "Sporting",
  height_cm: { min: 53, max: 64 },
  weight_kg: { min: 20, max: 32 },
  coat: { length: "short", type: "single", shedding: "low" },
  temperament: ["energetic","friendly","smart"],
  anatomy: { body: "athletic", ears: "drop", tail: "medium", eyes: "brown" }
},
{
  name: "German Wirehaired Pointer",
  lifeSpan: "12-14",
  origin: "Germany",
  type: "Sporting",
  height_cm: { min: 57, max: 68 },
  weight_kg: { min: 20, max: 34 },
  coat: { length: "wire", type: "double", shedding: "medium" },
  temperament: ["loyal","active","intelligent"],
  anatomy: { body: "rugged", ears: "drop", tail: "medium", eyes: "dark" }
},
{
  name: "Giant Schnauzer",
  lifeSpan: "10-12",
  origin: "Germany",
  type: "Working",
  height_cm: { min: 60, max: 70 },
  weight_kg: { min: 25, max: 48 },
  coat: { length: "wire", type: "double", shedding: "low" },
  temperament: ["dominant","loyal","alert"],
  anatomy: { body: "powerful", ears: "cropped", tail: "short", eyes: "dark" }
},
{
  name: "Glen of Imaal Terrier",
  lifeSpan: "10-15",
  origin: "Ireland",
  type: "Terrier",
  height_cm: { min: 30, max: 36 },
  weight_kg: { min: 14, max: 18 },
  coat: { length: "medium", type: "wire", shedding: "low" },
  temperament: ["calm","brave","independent"],
  anatomy: { body: "low", ears: "folded", tail: "medium", eyes: "round" }
},
{
  name: "Golden Retriever",
  lifeSpan: "10-12",
  origin: "Scotland",
  type: "Sporting",
  height_cm: { min: 51, max: 61 },
  weight_kg: { min: 25, max: 34 },
  coat: { length: "long", type: "double", shedding: "high" },
  temperament: ["friendly","gentle","intelligent"],
  anatomy: { body: "balanced", ears: "drop", tail: "feathered", eyes: "brown" }
},
{
  name: "Gordon Setter",
  lifeSpan: "10-12",
  origin: "Scotland",
  type: "Sporting",
  height_cm: { min: 58, max: 69 },
  weight_kg: { min: 20, max: 36 },
  coat: { length: "long", type: "silky", shedding: "medium" },
  temperament: ["loyal","active","confident"],
  anatomy: { body: "strong", ears: "long", tail: "feathered", eyes: "dark" }
},
{
  name: "Great Dane",
  lifeSpan: "7-10",
  origin: "Germany",
  type: "Working",
  height_cm: { min: 71, max: 86 },
  weight_kg: { min: 45, max: 90 },
  coat: { length: "short", type: "single", shedding: "medium" },
  temperament: ["gentle","friendly","calm"],
  anatomy: { body: "giant", ears: "drop", tail: "long", eyes: "dark" }
},
{
  name: "Great Pyrenees",
  lifeSpan: "10-12",
  origin: "France",
  type: "Working",
  height_cm: { min: 65, max: 82 },
  weight_kg: { min: 39, max: 54 },
  coat: { length: "long", type: "double", shedding: "high" },
  temperament: ["calm","protective","patient"],
  anatomy: { body: "large", ears: "drop", tail: "plumed", eyes: "dark" }
},
{
  name: "Greater Swiss Mountain Dog",
  lifeSpan: "8-11",
  origin: "Switzerland",
  type: "Working",
  height_cm: { min: 60, max: 72 },
  weight_kg: { min: 38, max: 64 },
  coat: { length: "short", type: "double", shedding: "medium" },
  temperament: ["loyal","calm","alert"],
  anatomy: { body: "strong", ears: "drop", tail: "long", eyes: "dark" }
},
{
  name: "Greyhound",
  lifeSpan: "10-14",
  origin: "Egypt",
  type: "Hound",
  height_cm: { min: 68, max: 76 },
  weight_kg: { min: 27, max: 40 },
  coat: { length: "short", type: "single", shedding: "low" },
  temperament: ["gentle","calm","independent"],
  anatomy: { body: "slim", ears: "folded", tail: "long", eyes: "dark" }
},

{
  name: "Hamiltonstovare",
  lifeSpan: "12-14",
  origin: "Sweden",
  type: "Hound",
  height_cm: { min: 49, max: 61 },
  weight_kg: { min: 23, max: 27 },
  coat: { length: "short", type: "double", shedding: "medium" },
  temperament: ["energetic","friendly","independent"],
  anatomy: { body: "balanced", ears: "drop", tail: "long", eyes: "dark" }
},
{
  name: "Hanoverian Scenthound",
  lifeSpan: "10-14",
  origin: "Germany",
  type: "Hound",
  height_cm: { min: 48, max: 55 },
  weight_kg: { min: 25, max: 40 },
  coat: { length: "short", type: "single", shedding: "low" },
  temperament: ["calm","loyal","focused"],
  anatomy: { body: "strong", ears: "long", tail: "medium", eyes: "dark" }
},
{
  name: "Harrier",
  lifeSpan: "12-15",
  origin: "England",
  type: "Hound",
  height_cm: { min: 48, max: 55 },
  weight_kg: { min: 20, max: 27 },
  coat: { length: "short", type: "single", shedding: "medium" },
  temperament: ["friendly","active","outgoing"],
  anatomy: { body: "compact", ears: "drop", tail: "long", eyes: "brown" }
},
{
  name: "Havanese",
  lifeSpan: "14-16",
  origin: "Cuba",
  type: "Toy",
  height_cm: { min: 23, max: 27 },
  weight_kg: { min: 3, max: 6 },
  coat: { length: "long", type: "silky", shedding: "low" },
  temperament: ["friendly","playful","affectionate"],
  anatomy: { body: "small", ears: "drop", tail: "curled", eyes: "large" }
},
{
  name: "Hokkaido",
  lifeSpan: "12-15",
  origin: "Japan",
  type: "Working",
  height_cm: { min: 45, max: 52 },
  weight_kg: { min: 20, max: 30 },
  coat: { length: "medium", type: "double", shedding: "high" },
  temperament: ["brave","loyal","alert"],
  anatomy: { body: "strong", ears: "erect", tail: "curled", eyes: "dark" }
},
{
  name: "Hovawart",
  lifeSpan: "10-14",
  origin: "Germany",
  type: "Working",
  height_cm: { min: 58, max: 70 },
  weight_kg: { min: 25, max: 40 },
  coat: { length: "long", type: "double", shedding: "medium" },
  temperament: ["loyal","protective","intelligent"],
  anatomy: { body: "strong", ears: "drop", tail: "long", eyes: "dark" }
},
{
  name: "Kuvasz",
  lifeSpan: "10-12",
  origin: "Hungary",
  type: "Working",
  height_cm: { min: 66, max: 76 },
  weight_kg: { min: 32, max: 52 },
  coat: { length: "long", type: "double", shedding: "high" },
  temperament: ["independent","protective","loyal"],
  anatomy: { body: "large", ears: "drop", tail: "long", eyes: "dark" }
},
{
  name: "Hungarian Vizsla",
  lifeSpan: "12-14",
  origin: "Hungary",
  type: "Sporting",
  height_cm: { min: 53, max: 64 },
  weight_kg: { min: 20, max: 30 },
  coat: { length: "short", type: "single", shedding: "low" },
  temperament: ["affectionate","energetic","loyal"],
  anatomy: { body: "lean", ears: "drop", tail: "medium", eyes: "amber" }
},
{
  name: "Wirehaired Vizsla",
  lifeSpan: "12-14",
  origin: "Hungary",
  type: "Sporting",
  height_cm: { min: 53, max: 64 },
  weight_kg: { min: 20, max: 30 },
  coat: { length: "wire", type: "double", shedding: "low" },
  temperament: ["loyal","gentle","active"],
  anatomy: { body: "lean", ears: "drop", tail: "medium", eyes: "brown" }
},
{
  name: "Siberian Husky",
  lifeSpan: "12-14",
  origin: "Siberia",
  type: "Working",
  height_cm: { min: 50, max: 60 },
  weight_kg: { min: 16, max: 27 },
  coat: { length: "medium", type: "double", shedding: "high" },
  temperament: ["friendly","energetic","independent"],
  anatomy: { body: "athletic", ears: "erect", tail: "bushy", eyes: "blue/brown" }
},

{
  name: "Ibizan Hound",
  lifeSpan: "11-14",
  origin: "Spain",
  type: "Hound",
  height_cm: { min: 56, max: 74 },
  weight_kg: { min: 20, max: 29 },
  coat: { length: "short/wire", type: "single", shedding: "low" },
  temperament: ["independent","alert","playful"],
  anatomy: { body: "slim", ears: "large erect", tail: "long", eyes: "amber" }
},
{
  name: "Icelandic Sheepdog",
  lifeSpan: "12-14",
  origin: "Iceland",
  type: "Herding",
  height_cm: { min: 40, max: 46 },
  weight_kg: { min: 9, max: 14 },
  coat: { length: "medium", type: "double", shedding: "high" },
  temperament: ["friendly","alert","playful"],
  anatomy: { body: "compact", ears: "erect", tail: "curled", eyes: "dark" }
},
{
  name: "Indian Pariah Dog",
  lifeSpan: "12-16",
  origin: "India",
  type: "Primitive",
  height_cm: { min: 50, max: 65 },
  weight_kg: { min: 15, max: 30 },
  coat: { length: "short", type: "single", shedding: "low" },
  temperament: ["intelligent","independent","alert"],
  anatomy: { body: "lean", ears: "erect", tail: "curved", eyes: "dark" }
},
{
  name: "Indian Spitz",
  lifeSpan: "10-14",
  origin: "India",
  type: "Toy",
  height_cm: { min: 20, max: 25 },
  weight_kg: { min: 5, max: 10 },
  coat: { length: "medium", type: "double", shedding: "medium" },
  temperament: ["playful","intelligent","friendly"],
  anatomy: { body: "small", ears: "erect", tail: "curled", eyes: "dark" }
},
{
  name: "Irish Red and White Setter",
  lifeSpan: "11-15",
  origin: "Ireland",
  type: "Sporting",
  height_cm: { min: 57, max: 66 },
  weight_kg: { min: 25, max: 34 },
  coat: { length: "long", type: "silky", shedding: "medium" },
  temperament: ["friendly","active","loyal"],
  anatomy: { body: "athletic", ears: "drop", tail: "feathered", eyes: "dark" }
},
{
  name: "Irish Setter",
  lifeSpan: "12-15",
  origin: "Ireland",
  type: "Sporting",
  height_cm: { min: 58, max: 67 },
  weight_kg: { min: 25, max: 34 },
  coat: { length: "long", type: "silky", shedding: "medium" },
  temperament: ["friendly","energetic","outgoing"],
  anatomy: { body: "slim", ears: "long", tail: "feathered", eyes: "dark" }
},
{
  name: "Irish Terrier",
  lifeSpan: "13-15",
  origin: "Ireland",
  type: "Terrier",
  height_cm: { min: 45, max: 48 },
  weight_kg: { min: 11, max: 12 },
  coat: { length: "wire", type: "single", shedding: "low" },
  temperament: ["bold","loyal","spirited"],
  anatomy: { body: "compact", ears: "folded", tail: "upright", eyes: "dark" }
},
{
  name: "Irish Water Spaniel",
  lifeSpan: "10-12",
  origin: "Ireland",
  type: "Sporting",
  height_cm: { min: 51, max: 61 },
  weight_kg: { min: 20, max: 30 },
  coat: { length: "curly", type: "single", shedding: "low" },
  temperament: ["playful","intelligent","active"],
  anatomy: { body: "strong", ears: "long", tail: "rat tail", eyes: "dark" }
},
{
  name: "Irish Wolfhound",
  lifeSpan: "6-8",
  origin: "Ireland",
  type: "Hound",
  height_cm: { min: 76, max: 86 },
  weight_kg: { min: 48, max: 70 },
  coat: { length: "rough", type: "single", shedding: "low" },
  temperament: ["gentle","friendly","calm"],
  anatomy: { body: "giant", ears: "folded", tail: "long", eyes: "dark" }
},
{
  name: "Italian Greyhound",
  lifeSpan: "12-15",
  origin: "Italy",
  type: "Toy",
  height_cm: { min: 32, max: 38 },
  weight_kg: { min: 3, max: 6 },
  coat: { length: "short", type: "single", shedding: "low" },
  temperament: ["affectionate","playful","sensitive"],
  anatomy: { body: "slim", ears: "folded", tail: "long", eyes: "large" }
},
{
  name: "Jack Russell Terrier",
  lifeSpan: "13-16",
  origin: "England",
  type: "Terrier",
  height_cm: { min: 25, max: 38 },
  weight_kg: { min: 6, max: 8 },
  coat: { length: "short/rough", type: "single", shedding: "medium" },
  temperament: ["energetic","bold","intelligent"],
  anatomy: { body: "compact", ears: "folded", tail: "upright", eyes: "dark" }
},
{
  name: "Japanese Chin",
  lifeSpan: "10-12",
  origin: "Japan",
  type: "Toy",
  height_cm: { min: 20, max: 28 },
  weight_kg: { min: 2, max: 5 },
  coat: { length: "long", type: "silky", shedding: "medium" },
  temperament: ["affectionate","calm","friendly"],
  anatomy: { body: "small", ears: "feathered", tail: "curled", eyes: "large" }
},
{
  name: "Japanese Spitz",
  lifeSpan: "12-14",
  origin: "Japan",
  type: "Non-Sporting",
  height_cm: { min: 30, max: 38 },
  weight_kg: { min: 5, max: 10 },
  coat: { length: "long", type: "double", shedding: "high" },
  temperament: ["playful","loyal","alert"],
  anatomy: { body: "compact", ears: "erect", tail: "curled", eyes: "dark" }
},
{
  name: "Jindo",
  lifeSpan: "12-15",
  origin: "South Korea",
  type: "Working",
  height_cm: { min: 45, max: 55 },
  weight_kg: { min: 15, max: 23 },
  coat: { length: "short", type: "double", shedding: "high" },
  temperament: ["loyal","independent","alert"],
  anatomy: { body: "balanced", ears: "erect", tail: "curled", eyes: "dark" }
},

{
  name: "Kai Ken",
  lifeSpan: "12-15",
  origin: "Japan",
  type: "Working",
  height_cm: { min: 45, max: 56 },
  weight_kg: { min: 11, max: 25 },
  coat: { length: "medium", type: "double", shedding: "medium" },
  temperament: ["loyal","alert","agile"],
  anatomy: { body: "compact", ears: "erect", tail: "curled", eyes: "dark" }
},
{
  name: "Kangal Shepherd Dog",
  lifeSpan: "12-15",
  origin: "Turkey",
  type: "Working",
  height_cm: { min: 65, max: 78 },
  weight_kg: { min: 40, max: 65 },
  coat: { length: "short", type: "double", shedding: "medium" },
  temperament: ["protective","calm","loyal"],
  anatomy: { body: "large", ears: "drop", tail: "curled", eyes: "dark" }
},
{
  name: "Karelian Bear Dog",
  lifeSpan: "11-13",
  origin: "Finland",
  type: "Working",
  height_cm: { min: 49, max: 60 },
  weight_kg: { min: 20, max: 28 },
  coat: { length: "short", type: "double", shedding: "medium" },
  temperament: ["brave","independent","alert"],
  anatomy: { body: "strong", ears: "erect", tail: "curled", eyes: "dark" }
},
{
  name: "Karst Shepherd",
  lifeSpan: "10-12",
  origin: "Slovenia",
  type: "Working",
  height_cm: { min: 54, max: 63 },
  weight_kg: { min: 25, max: 42 },
  coat: { length: "medium", type: "double", shedding: "medium" },
  temperament: ["loyal","calm","protective"],
  anatomy: { body: "strong", ears: "drop", tail: "bushy", eyes: "dark" }
},
{
  name: "Keeshond",
  lifeSpan: "12-15",
  origin: "Netherlands",
  type: "Non-Sporting",
  height_cm: { min: 43, max: 46 },
  weight_kg: { min: 14, max: 18 },
  coat: { length: "long", type: "double", shedding: "high" },
  temperament: ["friendly","alert","playful"],
  anatomy: { body: "compact", ears: "erect", tail: "curled", eyes: "dark" }
},
{
  name: "Kerry Blue Terrier",
  lifeSpan: "12-15",
  origin: "Ireland",
  type: "Terrier",
  height_cm: { min: 44, max: 49 },
  weight_kg: { min: 15, max: 18 },
  coat: { length: "curly", type: "single", shedding: "low" },
  temperament: ["energetic","intelligent","alert"],
  anatomy: { body: "muscular", ears: "folded", tail: "upright", eyes: "dark" }
},
{
  name: "Komondor",
  lifeSpan: "10-12",
  origin: "Hungary",
  type: "Working",
  height_cm: { min: 65, max: 80 },
  weight_kg: { min: 40, max: 60 },
  coat: { length: "corded", type: "double", shedding: "low" },
  temperament: ["protective","calm","loyal"],
  anatomy: { body: "large", ears: "drop", tail: "curved", eyes: "dark" }
},
{
  name: "Kooikerhondje",
  lifeSpan: "12-14",
  origin: "Netherlands",
  type: "Sporting",
  height_cm: { min: 35, max: 40 },
  weight_kg: { min: 9, max: 11 },
  coat: { length: "medium", type: "double", shedding: "medium" },
  temperament: ["friendly","alert","active"],
  anatomy: { body: "compact", ears: "feathered", tail: "plumed", eyes: "dark" }
},
{
  name: "Korean Mastiff",
  lifeSpan: "7-12",
  origin: "South Korea",
  type: "Working",
  height_cm: { min: 60, max: 75 },
  weight_kg: { min: 50, max: 80 },
  coat: { length: "short", type: "single", shedding: "low" },
  temperament: ["calm","protective","loyal"],
  anatomy: { body: "massive", ears: "drop", tail: "thick", eyes: "dark" }
},
{
  name: "Kuvasz",
  lifeSpan: "10-12",
  origin: "Hungary",
  type: "Working",
  height_cm: { min: 66, max: 76 },
  weight_kg: { min: 32, max: 52 },
  coat: { length: "long", type: "double", shedding: "high" },
  temperament: ["independent","protective","loyal"],
  anatomy: { body: "large", ears: "drop", tail: "long", eyes: "dark" }
},

{
  name: "Labrador Retriever",
  lifeSpan: "10-12",
  origin: "Canada",
  type: "Sporting",
  height_cm: { min: 54, max: 62 },
  weight_kg: { min: 25, max: 36 },
  coat: { length: "short", type: "double", shedding: "high" },
  temperament: ["friendly","outgoing","intelligent"],
  anatomy: { body: "strong", ears: "drop", tail: "otter", eyes: "brown" }
},
{
  name: "Lagotto Romagnolo",
  lifeSpan: "14-17",
  origin: "Italy",
  type: "Sporting",
  height_cm: { min: 41, max: 48 },
  weight_kg: { min: 11, max: 16 },
  coat: { length: "curly", type: "double", shedding: "low" },
  temperament: ["affectionate","alert","intelligent"],
  anatomy: { body: "compact", ears: "drop", tail: "medium", eyes: "round" }
},
{
  name: "Lakeland Terrier",
  lifeSpan: "12-15",
  origin: "England",
  type: "Terrier",
  height_cm: { min: 33, max: 38 },
  weight_kg: { min: 7, max: 8 },
  coat: { length: "wire", type: "single", shedding: "low" },
  temperament: ["bold","friendly","confident"],
  anatomy: { body: "compact", ears: "folded", tail: "upright", eyes: "dark" }
},
{
  name: "Lancashire Heeler",
  lifeSpan: "12-15",
  origin: "England",
  type: "Herding",
  height_cm: { min: 25, max: 30 },
  weight_kg: { min: 6, max: 8 },
  coat: { length: "short", type: "double", shedding: "medium" },
  temperament: ["energetic","loyal","alert"],
  anatomy: { body: "small", ears: "erect", tail: "medium", eyes: "dark" }
},
{
  name: "Leonberger",
  lifeSpan: "8-9",
  origin: "Germany",
  type: "Working",
  height_cm: { min: 65, max: 80 },
  weight_kg: { min: 45, max: 75 },
  coat: { length: "long", type: "double", shedding: "high" },
  temperament: ["gentle","friendly","calm"],
  anatomy: { body: "giant", ears: "drop", tail: "long", eyes: "dark" }
},
{
  name: "Lhasa Apso",
  lifeSpan: "12-15",
  origin: "Tibet",
  type: "Toy",
  height_cm: { min: 25, max: 28 },
  weight_kg: { min: 5, max: 8 },
  coat: { length: "long", type: "double", shedding: "low" },
  temperament: ["independent","alert","loyal"],
  anatomy: { body: "small", ears: "long", tail: "curled", eyes: "dark" }
},
{
  name: "Lowchen",
  lifeSpan: "13-15",
  origin: "Germany/France",
  type: "Toy",
  height_cm: { min: 25, max: 33 },
  weight_kg: { min: 4, max: 8 },
  coat: { length: "long", type: "single", shedding: "low" },
  temperament: ["playful","affectionate","friendly"],
  anatomy: { body: "small", ears: "drop", tail: "curved", eyes: "dark" }
},

{
  name: "Maltese",
  lifeSpan: "12-15",
  origin: "Malta",
  type: "Toy",
  height_cm: { min: 20, max: 25 },
  weight_kg: { min: 3, max: 4 },
  coat: { length: "long", type: "silky", shedding: "low" },
  temperament: ["gentle","playful","affectionate"],
  anatomy: { body: "small", ears: "drop", tail: "curved", eyes: "dark" }
},
{
  name: "Manchester Terrier",
  lifeSpan: "14-16",
  origin: "England",
  type: "Terrier",
  height_cm: { min: 38, max: 41 },
  weight_kg: { min: 5, max: 10 },
  coat: { length: "short", type: "single", shedding: "low" },
  temperament: ["alert","intelligent","active"],
  anatomy: { body: "sleek", ears: "erect", tail: "long", eyes: "dark" }
},
{
  name: "Maremma Sheepdog",
  lifeSpan: "11-13",
  origin: "Italy",
  type: "Working",
  height_cm: { min: 60, max: 73 },
  weight_kg: { min: 30, max: 45 },
  coat: { length: "long", type: "double", shedding: "high" },
  temperament: ["protective","loyal","calm"],
  anatomy: { body: "large", ears: "drop", tail: "bushy", eyes: "dark" }
},
{
  name: "Mastiff",
  lifeSpan: "6-10",
  origin: "England",
  type: "Working",
  height_cm: { min: 70, max: 91 },
  weight_kg: { min: 54, max: 100 },
  coat: { length: "short", type: "single", shedding: "medium" },
  temperament: ["gentle","protective","calm"],
  anatomy: { body: "massive", ears: "drop", tail: "thick", eyes: "dark" }
},
{
  name: "Miniature Bull Terrier",
  lifeSpan: "11-13",
  origin: "England",
  type: "Terrier",
  height_cm: { min: 25, max: 35 },
  weight_kg: { min: 9, max: 16 },
  coat: { length: "short", type: "single", shedding: "low" },
  temperament: ["playful","stubborn","energetic"],
  anatomy: { body: "muscular", ears: "erect", tail: "short", eyes: "triangular" }
},
{
  name: "Miniature Pinscher",
  lifeSpan: "12-16",
  origin: "Germany",
  type: "Toy",
  height_cm: { min: 25, max: 30 },
  weight_kg: { min: 4, max: 6 },
  coat: { length: "short", type: "single", shedding: "low" },
  temperament: ["energetic","bold","alert"],
  anatomy: { body: "small", ears: "erect", tail: "short", eyes: "dark" }
},
{
  name: "Miniature Schnauzer",
  lifeSpan: "12-15",
  origin: "Germany",
  type: "Terrier",
  height_cm: { min: 30, max: 36 },
  weight_kg: { min: 5, max: 9 },
  coat: { length: "wire", type: "double", shedding: "low" },
  temperament: ["friendly","alert","obedient"],
  anatomy: { body: "compact", ears: "folded", tail: "short", eyes: "dark" }
},
{
  name: "Mountain Cur",
  lifeSpan: "10-13",
  origin: "USA",
  type: "Working",
  height_cm: { min: 40, max: 66 },
  weight_kg: { min: 14, max: 27 },
  coat: { length: "short", type: "single", shedding: "low" },
  temperament: ["loyal","protective","energetic"],
  anatomy: { body: "athletic", ears: "drop", tail: "medium", eyes: "dark" }
},
{
  name: "Mudi",
  lifeSpan: "12-14",
  origin: "Hungary",
  type: "Herding",
  height_cm: { min: 38, max: 47 },
  weight_kg: { min: 8, max: 13 },
  coat: { length: "curly", type: "double", shedding: "medium" },
  temperament: ["intelligent","active","alert"],
  anatomy: { body: "compact", ears: "erect", tail: "curved", eyes: "dark" }
},

{
  name: "Neapolitan Mastiff",
  lifeSpan: "7-9",
  origin: "Italy",
  type: "Working",
  height_cm: { min: 60, max: 75 },
  weight_kg: { min: 50, max: 70 },
  coat: { length: "short", type: "single", shedding: "low" },
  temperament: ["protective","calm","loyal"],
  anatomy: { body: "massive", ears: "drop", tail: "thick", eyes: "dark" }
},
{
  name: "Newfoundland",
  lifeSpan: "8-10",
  origin: "Canada",
  type: "Working",
  height_cm: { min: 66, max: 71 },
  weight_kg: { min: 45, max: 68 },
  coat: { length: "long", type: "double", shedding: "high" },
  temperament: ["gentle","friendly","calm"],
  anatomy: { body: "large", ears: "drop", tail: "bushy", eyes: "dark" }
},
{
  name: "Norfolk Terrier",
  lifeSpan: "12-15",
  origin: "England",
  type: "Terrier",
  height_cm: { min: 23, max: 25 },
  weight_kg: { min: 5, max: 6 },
  coat: { length: "wire", type: "single", shedding: "low" },
  temperament: ["friendly","alert","active"],
  anatomy: { body: "small", ears: "drop", tail: "medium", eyes: "dark" }
},
{
  name: "Norwegian Buhund",
  lifeSpan: "12-15",
  origin: "Norway",
  type: "Herding",
  height_cm: { min: 41, max: 47 },
  weight_kg: { min: 12, max: 18 },
  coat: { length: "medium", type: "double", shedding: "high" },
  temperament: ["friendly","energetic","alert"],
  anatomy: { body: "compact", ears: "erect", tail: "curled", eyes: "dark" }
},
{
  name: "Norwegian Elkhound",
  lifeSpan: "12-15",
  origin: "Norway",
  type: "Hound",
  height_cm: { min: 46, max: 52 },
  weight_kg: { min: 20, max: 25 },
  coat: { length: "medium", type: "double", shedding: "high" },
  temperament: ["bold","loyal","independent"],
  anatomy: { body: "compact", ears: "erect", tail: "curled", eyes: "dark" }
},
{
  name: "Norwegian Lundehund",
  lifeSpan: "12-15",
  origin: "Norway",
  type: "Non-Sporting",
  height_cm: { min: 30, max: 38 },
  weight_kg: { min: 6, max: 9 },
  coat: { length: "short", type: "double", shedding: "medium" },
  temperament: ["alert","playful","independent"],
  anatomy: { body: "flexible", ears: "erect", tail: "curled", eyes: "dark" }
},
{
  name: "Norwich Terrier",
  lifeSpan: "12-15",
  origin: "England",
  type: "Terrier",
  height_cm: { min: 24, max: 26 },
  weight_kg: { min: 5, max: 6 },
  coat: { length: "wire", type: "single", shedding: "low" },
  temperament: ["playful","friendly","alert"],
  anatomy: { body: "small", ears: "erect", tail: "medium", eyes: "dark" }
},
{
  name: "Nova Scotia Duck Tolling Retriever",
  lifeSpan: "12-14",
  origin: "Canada",
  type: "Sporting",
  height_cm: { min: 45, max: 53 },
  weight_kg: { min: 17, max: 23 },
  coat: { length: "medium", type: "double", shedding: "medium" },
  temperament: ["energetic","intelligent","friendly"],
  anatomy: { body: "compact", ears: "drop", tail: "bushy", eyes: "amber" }
},
{
  name: "Old English Sheepdog",
  lifeSpan: "10-12",
  origin: "England",
  type: "Herding",
  height_cm: { min: 56, max: 61 },
  weight_kg: { min: 27, max: 45 },
  coat: { length: "long", type: "double", shedding: "high" },
  temperament: ["friendly","gentle","playful"],
  anatomy: { body: "large", ears: "drop", tail: "docked", eyes: "dark" }
},
{
  name: "Otterhound",
  lifeSpan: "10-13",
  origin: "England",
  type: "Hound",
  height_cm: { min: 61, max: 69 },
  weight_kg: { min: 30, max: 54 },
  coat: { length: "rough", type: "double", shedding: "medium" },
  temperament: ["friendly","independent","energetic"],
  anatomy: { body: "strong", ears: "long", tail: "long", eyes: "dark" }
},
{
  name: "Papillon",
  lifeSpan: "13-15",
  origin: "France",
  type: "Toy",
  height_cm: { min: 20, max: 28 },
  weight_kg: { min: 3, max: 5 },
  coat: { length: "long", type: "silky", shedding: "low" },
  temperament: ["friendly","alert","intelligent"],
  anatomy: { body: "small", ears: "butterfly", tail: "plumed", eyes: "dark" }
},
{
  name: "Parson Russell Terrier",
  lifeSpan: "13-15",
  origin: "England",
  type: "Terrier",
  height_cm: { min: 30, max: 36 },
  weight_kg: { min: 6, max: 8 },
  coat: { length: "short/rough", type: "single", shedding: "medium" },
  temperament: ["energetic","bold","smart"],
  anatomy: { body: "compact", ears: "folded", tail: "upright", eyes: "dark" }
},
{
  name: "Pekingese",
  lifeSpan: "12-14",
  origin: "China",
  type: "Toy",
  height_cm: { min: 15, max: 23 },
  weight_kg: { min: 3, max: 6 },
  coat: { length: "long", type: "double", shedding: "medium" },
  temperament: ["independent","loyal","calm"],
  anatomy: { body: "small", ears: "long", tail: "curled", eyes: "large" }
},
{
  name: "Pembroke Welsh Corgi",
  lifeSpan: "12-15",
  origin: "Wales",
  type: "Herding",
  height_cm: { min: 25, max: 30 },
  weight_kg: { min: 10, max: 14 },
  coat: { length: "medium", type: "double", shedding: "high" },
  temperament: ["playful","intelligent","friendly"],
  anatomy: { body: "long", ears: "erect", tail: "short", eyes: "dark" }
},
{
  name: "Peruvian Inca Orchid",
  lifeSpan: "12-14",
  origin: "Peru",
  type: "Non-Sporting",
  height_cm: { min: 25, max: 65 },
  weight_kg: { min: 4, max: 25 },
  coat: { length: "hairless/short", type: "single", shedding: "low" },
  temperament: ["alert","loyal","sensitive"],
  anatomy: { body: "slim", ears: "erect", tail: "long", eyes: "dark" }
},
{
  name: "Petit Basset Griffon Vendéen",
  lifeSpan: "14-16",
  origin: "France",
  type: "Hound",
  height_cm: { min: 34, max: 38 },
  weight_kg: { min: 11, max: 18 },
  coat: { length: "rough", type: "double", shedding: "medium" },
  temperament: ["friendly","active","curious"],
  anatomy: { body: "short", ears: "long", tail: "upright", eyes: "dark" }
},
{
  name: "Pharaoh Hound",
  lifeSpan: "11-14",
  origin: "Malta",
  type: "Hound",
  height_cm: { min: 53, max: 63 },
  weight_kg: { min: 18, max: 27 },
  coat: { length: "short", type: "single", shedding: "low" },
  temperament: ["friendly","alert","playful"],
  anatomy: { body: "lean", ears: "erect", tail: "long", eyes: "amber" }
},
{
  name: "Plott Hound",
  lifeSpan: "12-14",
  origin: "USA",
  type: "Hound",
  height_cm: { min: 51, max: 64 },
  weight_kg: { min: 18, max: 27 },
  coat: { length: "short", type: "single", shedding: "low" },
  temperament: ["bold","loyal","alert"],
  anatomy: { body: "muscular", ears: "drop", tail: "long", eyes: "dark" }
},
{
  name: "Pointer",
  lifeSpan: "12-17",
  origin: "England",
  type: "Sporting",
  height_cm: { min: 53, max: 71 },
  weight_kg: { min: 20, max: 34 },
  coat: { length: "short", type: "single", shedding: "low" },
  temperament: ["friendly","energetic","loyal"],
  anatomy: { body: "lean", ears: "drop", tail: "long", eyes: "brown" }
},
{
  name: "Polish Lowland Sheepdog",
  lifeSpan: "10-12",
  origin: "Poland",
  type: "Herding",
  height_cm: { min: 42, max: 50 },
  weight_kg: { min: 14, max: 23 },
  coat: { length: "long", type: "double", shedding: "medium" },
  temperament: ["confident","loyal","alert"],
  anatomy: { body: "compact", ears: "drop", tail: "short", eyes: "dark" }
},
{
  name: "Pomeranian",
  lifeSpan: "12-16",
  origin: "Germany",
  type: "Toy",
  height_cm: { min: 18, max: 24 },
  weight_kg: { min: 2, max: 3.5 },
  coat: { length: "long", type: "double", shedding: "high" },
  temperament: ["playful","alert","extroverted"],
  anatomy: { body: "small", ears: "erect", tail: "curled", eyes: "dark" }
},
{
  name: "Poodle",
  lifeSpan: "12-15",
  origin: "Germany/France",
  type: "Non-Sporting",
  height_cm: { min: 24, max: 60 },
  weight_kg: { min: 4, max: 32 },
  coat: { length: "curly", type: "single", shedding: "low" },
  temperament: ["intelligent","active","alert"],
  anatomy: { body: "elegant", ears: "long", tail: "curved", eyes: "dark" }
},
{
  name: "Portuguese Water Dog",
  lifeSpan: "11-13",
  origin: "Portugal",
  type: "Working",
  height_cm: { min: 43, max: 57 },
  weight_kg: { min: 16, max: 27 },
  coat: { length: "curly/wavy", type: "single", shedding: "low" },
  temperament: ["energetic","intelligent","loyal"],
  anatomy: { body: "athletic", ears: "drop", tail: "curved", eyes: "dark" }
},
{
  name: "Pug",
  lifeSpan: "12-15",
  origin: "China",
  type: "Toy",
  height_cm: { min: 25, max: 30 },
  weight_kg: { min: 6, max: 8 },
  coat: { length: "short", type: "single", shedding: "high" },
  temperament: ["playful","friendly","charming"],
  anatomy: { body: "compact", ears: "folded", tail: "curled", eyes: "large" }
},
{
  name: "Puli",
  lifeSpan: "12-16",
  origin: "Hungary",
  type: "Herding",
  height_cm: { min: 36, max: 45 },
  weight_kg: { min: 10, max: 15 },
  coat: { length: "corded", type: "double", shedding: "low" },
  temperament: ["loyal","energetic","alert"],
  anatomy: { body: "compact", ears: "drop", tail: "curled", eyes: "dark" }
},
{
  name: "Pumi",
  lifeSpan: "12-14",
  origin: "Hungary",
  type: "Herding",
  height_cm: { min: 38, max: 47 },
  weight_kg: { min: 8, max: 13 },
  coat: { length: "curly", type: "double", shedding: "low" },
  temperament: ["energetic","alert","intelligent"],
  anatomy: { body: "compact", ears: "semi-erect", tail: "curled", eyes: "dark" }
},

{
  name: "Qatari Saluki",
  lifeSpan: "12-14",
  origin: "Qatar",
  type: "Hound",
  height_cm: { min: 58, max: 71 },
  weight_kg: { min: 18, max: 27 },
  coat: { length: "short", type: "single", shedding: "low" },
  temperament: ["gentle","independent","loyal"],
  anatomy: { body: "slim", ears: "long", tail: "feathered", eyes: "dark" }
},

{
  name: "Rat Terrier",
  lifeSpan: "12-18",
  origin: "USA",
  type: "Terrier",
  height_cm: { min: 25, max: 46 },
  weight_kg: { min: 5, max: 11 },
  coat: { length: "short", type: "single", shedding: "low" },
  temperament: ["energetic","alert","friendly"],
  anatomy: { body: "compact", ears: "erect", tail: "medium", eyes: "dark" }
},
{
  name: "Redbone Coonhound",
  lifeSpan: "10-12",
  origin: "USA",
  type: "Hound",
  height_cm: { min: 53, max: 69 },
  weight_kg: { min: 20, max: 32 },
  coat: { length: "short", type: "single", shedding: "low" },
  temperament: ["friendly","energetic","loyal"],
  anatomy: { body: "muscular", ears: "long", tail: "long", eyes: "dark" }
},
{
  name: "Rhodesian Ridgeback",
  lifeSpan: "10-12",
  origin: "Africa",
  type: "Hound",
  height_cm: { min: 61, max: 69 },
  weight_kg: { min: 29, max: 41 },
  coat: { length: "short", type: "single", shedding: "low" },
  temperament: ["loyal","independent","protective"],
  anatomy: { body: "strong", ears: "drop", tail: "long", eyes: "dark" }
},
{
  name: "Rottweiler",
  lifeSpan: "8-10",
  origin: "Germany",
  type: "Working",
  height_cm: { min: 56, max: 69 },
  weight_kg: { min: 35, max: 60 },
  coat: { length: "short", type: "double", shedding: "medium" },
  temperament: ["loyal","protective","confident"],
  anatomy: { body: "muscular", ears: "drop", tail: "short", eyes: "dark" }
},

{
  name: "Saint Bernard",
  lifeSpan: "8-10",
  origin: "Switzerland",
  type: "Working",
  height_cm: { min: 65, max: 90 },
  weight_kg: { min: 50, max: 120 },
  coat: { length: "long/short", type: "double", shedding: "high" },
  temperament: ["gentle","friendly","calm"],
  anatomy: { body: "giant", ears: "drop", tail: "long", eyes: "dark" }
},
{
  name: "Saluki",
  lifeSpan: "10-17",
  origin: "Middle East",
  type: "Hound",
  height_cm: { min: 58, max: 71 },
  weight_kg: { min: 18, max: 27 },
  coat: { length: "short/feathered", type: "single", shedding: "low" },
  temperament: ["gentle","independent","quiet"],
  anatomy: { body: "slim", ears: "long", tail: "feathered", eyes: "dark" }
},
{
  name: "Samoyed",
  lifeSpan: "12-14",
  origin: "Siberia",
  type: "Working",
  height_cm: { min: 48, max: 60 },
  weight_kg: { min: 16, max: 30 },
  coat: { length: "long", type: "double", shedding: "high" },
  temperament: ["friendly","gentle","playful"],
  anatomy: { body: "strong", ears: "erect", tail: "curled", eyes: "dark" }
},
{
  name: "Schipperke",
  lifeSpan: "12-16",
  origin: "Belgium",
  type: "Non-Sporting",
  height_cm: { min: 25, max: 33 },
  weight_kg: { min: 3, max: 9 },
  coat: { length: "medium", type: "double", shedding: "medium" },
  temperament: ["curious","alert","confident"],
  anatomy: { body: "small", ears: "erect", tail: "short", eyes: "dark" }
},
{
  name: "Scottish Terrier",
  lifeSpan: "11-13",
  origin: "Scotland",
  type: "Terrier",
  height_cm: { min: 25, max: 28 },
  weight_kg: { min: 8, max: 10 },
  coat: { length: "wire", type: "double", shedding: "low" },
  temperament: ["independent","loyal","alert"],
  anatomy: { body: "compact", ears: "erect", tail: "upright", eyes: "dark" }
},
{
  name: "Shiba Inu",
  lifeSpan: "12-15",
  origin: "Japan",
  type: "Non-Sporting",
  height_cm: { min: 35, max: 43 },
  weight_kg: { min: 8, max: 11 },
  coat: { length: "short", type: "double", shedding: "high" },
  temperament: ["independent","alert","bold"],
  anatomy: { body: "compact", ears: "erect", tail: "curled", eyes: "dark" }
},
{
  name: "Shih Tzu",
  lifeSpan: "10-16",
  origin: "China",
  type: "Toy",
  height_cm: { min: 20, max: 28 },
  weight_kg: { min: 4, max: 7 },
  coat: { length: "long", type: "double", shedding: "low" },
  temperament: ["friendly","affectionate","playful"],
  anatomy: { body: "small", ears: "long", tail: "curled", eyes: "large" }
},
{
  name: "Siberian Husky",
  lifeSpan: "12-14",
  origin: "Siberia",
  type: "Working",
  height_cm: { min: 50, max: 60 },
  weight_kg: { min: 16, max: 27 },
  coat: { length: "medium", type: "double", shedding: "high" },
  temperament: ["friendly","energetic","independent"],
  anatomy: { body: "athletic", ears: "erect", tail: "bushy", eyes: "blue/brown" }
},
{
  name: "Silky Terrier",
  lifeSpan: "12-15",
  origin: "Australia",
  type: "Toy",
  height_cm: { min: 23, max: 26 },
  weight_kg: { min: 3.5, max: 4.5 },
  coat: { length: "long", type: "silky", shedding: "low" },
  temperament: ["alert","friendly","energetic"],
  anatomy: { body: "small", ears: "erect", tail: "medium", eyes: "dark" }
},
{
  name: "Skye Terrier",
  lifeSpan: "12-14",
  origin: "Scotland",
  type: "Terrier",
  height_cm: { min: 23, max: 26 },
  weight_kg: { min: 11, max: 18 },
  coat: { length: "long", type: "double", shedding: "medium" },
  temperament: ["loyal","calm","friendly"],
  anatomy: { body: "long", ears: "erect/drop", tail: "feathered", eyes: "dark" }
},
{
  name: "Sloughi",
  lifeSpan: "10-15",
  origin: "North Africa",
  type: "Hound",
  height_cm: { min: 61, max: 72 },
  weight_kg: { min: 20, max: 30 },
  coat: { length: "short", type: "single", shedding: "low" },
  temperament: ["reserved","loyal","gentle"],
  anatomy: { body: "slender", ears: "drop", tail: "long", eyes: "dark" }
},
{
  name: "Staffordshire Bull Terrier",
  lifeSpan: "12-14",
  origin: "England",
  type: "Terrier",
  height_cm: { min: 36, max: 41 },
  weight_kg: { min: 11, max: 17 },
  coat: { length: "short", type: "single", shedding: "low" },
  temperament: ["courageous","friendly","loyal"],
  anatomy: { body: "muscular", ears: "rose", tail: "medium", eyes: "round" }
},
{
  name: "Tibetan Mastiff",
  lifeSpan: "10-14",
  origin: "Tibet",
  type: "Working",
  height_cm: { min: 61, max: 76 },
  weight_kg: { min: 35, max: 70 },
  coat: { length: "long", type: "double", shedding: "high" },
  temperament: ["protective","independent","calm"],
  anatomy: { body: "giant", ears: "drop", tail: "curled", eyes: "deep" }
},
{
  name: "Toy Fox Terrier",
  lifeSpan: "13-15",
  origin: "USA",
  type: "Toy",
  height_cm: { min: 21, max: 29 },
  weight_kg: { min: 1.5, max: 3.5 },
  coat: { length: "short", type: "single", shedding: "low" },
  temperament: ["playful","alert","intelligent"],
  anatomy: { body: "small", ears: "erect", tail: "short", eyes: "round" }
},
{
  name: "Weimaraner", lifeSpan: "10-13", origin: "Germany", type: "Sporting",
  height_cm: { min: 58, max: 69 }, weight_kg: { min: 25, max: 40 }, coat: { length: "short", type: "single", shedding: "low" },
  temperament: ["energetic","loyal","intelligent"],  anatomy: { body: "athletic", ears: "long drop", tail: "short", eyes: "amber" }
},
{
  name: "Welsh Terrier", lifeSpan: "12-15", origin: "Wales", type: "Terrier",
  height_cm: { min: 36, max: 39 }, weight_kg: { min: 9, max: 10 }, coat: { length: "medium", type: "wire", shedding: "low" },
  temperament: ["friendly","active","alert"], anatomy: { body: "compact", ears: "folded", tail: "upright", eyes: "dark" }
},
{
  name: "Whippet", lifeSpan: "12-15", origin: "England", type: "Hound",
  height_cm: { min: 44, max: 51 }, weight_kg: { min: 11, max: 20 }, coat: { length: "short", type: "single", shedding: "low" },
  temperament: ["gentle","calm","friendly"], anatomy: { body: "slender", ears: "rose", tail: "long", eyes: "dark" }
},
{
  name: "Yorkshire Terrier", lifeSpan: "13-16", origin: "England", type: "Toy",
  height_cm: { min: 18, max: 23 }, weight_kg: { min: 2, max: 3 }, coat: { length: "long", type: "silky", shedding: "low" },
  temperament: ["bold","affectionate","alert"], anatomy: { body: "tiny", ears: "erect", tail: "medium", eyes: "bright" }
},
{
  name: "Zuchon", lifeSpan: "12-15", origin: "USA", type: "Companion / Designer", height_cm: { min: 23, max: 30 },
  weight_kg: { min: 4, max: 8 }, coat: { length: "medium-long", type: "soft/wavy", shedding: "low" },
  temperament: ["affectionate","playful","friendly","gentle"], anatomy: { body: "small", ears: "drop", tail: "curled", eyes: "round dark" }
}];

const breedsList =[ {   id:"1", list: dogBreeds,
                        title:"Explore to know more about your companion", 
                        description:`Dogs are the ultimate embodiment of unconditional love, loyalty, and joy, acting as constant companions who offer comfort and reduce stress. Known as "man's best friend," they are selfless creatures that live in the moment, providing unwavering trust and enhancing human lives with their playful, empathetic nature. `
                    } ]